#
#
# 1. https://hub.docker.com/r/linuxserver/qbittorrent
#
---

#version: 3.8

networks:
  traefik-proxy:
    attachable: true
    driver: overlay
    external: true

#volumes:

services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent-1
    environment:
      - PUID=500
      - PGID=50
      - TZ=America/Chicago
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - ./mounts/config/:/config
      - /mnt/fs1/Software/torrents:/downloads #optional
    ports:
      - 9090:8080
      - 6881:6881
      - 6881:6881/udp
    networks:
      - traefik-proxy
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.aria2-webui.rule=((Host(`qdownloads.fs1.home`)) && PathPrefix(`/`))"
      - "traefik.http.routers.aria2-webui.entrypoints=web"
      - "traefik.http.services.aria2-webui.loadbalancer.server.port=8080"
      - "traefik.http.routers.aria2-webui.service=aria2-webui"
      #- "traefik.http.routers.aria2-webui.tls.certresolver=staging-web-acme"
      # adding a slash to the end
      - "traefik.http.routers.qb.entrypoints=web"
      - "traefik.http.routers.qb.rule=PathPrefix(`/qb`)"
      - "traefik.http.middlewares.qb-redirect.redirectregex.regex=^(.*)/qb$$"
      - "traefik.http.middlewares.qb-redirect.redirectregex.replacement=$$1/qb/"
      - "traefik.http.middlewares.qb-strip.stripprefix.prefixes=/qb/"
      # appropriate header changes
      - "traefik.http.middlewares.qb-headers.headers.customrequestheaders.X-Frame-Options=SAMEORIGIN"
      - "traefik.http.middlewares.qb-headers.headers.customrequestheaders.Referer="
      - "traefik.http.middlewares.qb-headers.headers.customrequestheaders.Origin="
      - "traefik.http.routers.qb.middlewares=qb-strip,qb-redirect,qb-headers"
      # loadbalancer to *not* pass the host header
      - "traefik.http.services.qb.loadbalancer.server.port=8080"
      - "traefik.http.services.qb.loadbalancer.passhostheader=false"
      - "traefik.docker.network=traefik-proxy"
