#
#
# 1. https://hub.docker.com/r/linuxserver/qbittorrent
#
---

#version: 3.8

networks:
  traefik-proxy:
    attachable: true
    driver: overlay
    external: true

#volumes:

services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent-1
    environment:
      - PUID=500
      - PGID=50
      - TZ=America/Chicago
      - WEBUI_PORT=9090
      - TORRENTING_PORT=6881
    volumes:
      - ./mounts/config/:/config
      - /mnt/fs1/Software/torrents:/downloads #optional
    ports:
      - 9090:8080
      - 6881:6881
      - 6881:6881/udp
    networks:
      - traefik-proxy
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.aria2-webui.rule=((Host(`qdownloads.fs1.home`)) && PathPrefix(`/`))"
      - "traefik.http.routers.aria2-webui.entrypoints=web"
      - "traefik.http.services.aria2-webui.loadbalancer.server.port=8080"
      - "traefik.http.routers.aria2-webui.service=aria2-webui"
      #- "traefik.http.routers.aria2-webui.tls.certresolver=staging-web-acme"
